### ISSUE TITLE
Feature Request: Show UTC time in the nav bar.

### ISSUE THREAD

**Issue by zeroby0** [dernasherbrezon/r2cloud-ui#8]
Just like how Satnogs web does it: https://network.satnogs.org/
I think it's a nice way to know the relative time to observations at a glance.

Sorry about the many tickets 🙈

**Comment by dernasherbrezon** [comment]
The time and status displayed in the overview:

![Screen Shot 2020-07-14 at 9 39 43 PM](https://user-images.githubusercontent.com/1614424/89734839-7ac51380-da56-11ea-8ff8-ce7713e632d3.png)
