### ISSUE TITLE
Feature Request: Show max elevation and others in observation

### ISSUE THREAD

**Issue by zeroby0** [dernasherbrezon/r2cloud-ui#9]
Some of the observations end up being unable to decode. With the knowledge of max-elevation, we can determine if the problem was a low satellite pass. Also useful to know at what angles the antenna null start affecting the signal.

Thanks :)

**Comment by dernasherbrezon** [comment]
Added polar plot:

![Screen Shot 2020-08-15 at 3 26 30 PM](https://user-images.githubusercontent.com/1614424/90313648-8741e400-df0e-11ea-964e-652886ae2e13.png)
